# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-05-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0013_remove_analysis_published_by_analysis_authors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="name_staging",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="name_staging_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="name_staging_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="name_staging_pt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
