# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-10-25 14:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0024_alter_rawdatasource_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coverage",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="v1.area",
            ),
        ),
        migrations.CreateModel(
            name="ColumnOriginalName",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("name_pt", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_es", models.CharField(max_length=255, null=True)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_original_names",
                        to="v1.column",
                    ),
                ),
            ],
            options={
                "verbose_name": "Column Original Name",
                "verbose_name_plural": "Column Original Names",
                "db_table": "column_original_name",
            },
        ),
        migrations.AddField(
            model_name="coverage",
            name="column_original_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="v1.columnoriginalname",
            ),
        ),
    ]
