# -*- coding: utf-8 -*-
# Generated by Django 4.2.13 on 2024-06-26 11:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0033_remove_dataset_db_slug_remove_table_db_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("frequency", models.IntegerField()),
                ("latest", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="v1.entity",
                    ),
                ),
                (
                    "information_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="v1.informationrequest",
                    ),
                ),
                (
                    "raw_data_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="v1.rawdatasource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll",
                "verbose_name_plural": "Polls",
                "db_table": "poll",
                "ordering": ["frequency"],
            },
        ),
    ]
