# -*- coding: utf-8 -*-
# Generated by Django 4.2.13 on 2024-06-28 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0034_poll"),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="date_coverage_reference",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category__slug": "datetime"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="columns",
                to="v1.entity",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="entity",
            field=models.ForeignKey(
                limit_choices_to={"category__slug": "datetime"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="v1.entity",
            ),
        ),
    ]
