# Generated by Django 4.2.13 on 2024-07-03 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0034_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimerange',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datetime_ranges', to='v1.column'),
        ),
    ]
