# -*- coding: utf-8 -*-
# Generated by Django 4.2.14 on 2024-07-26 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0034_poll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to="v1.entity",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="update",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="v1.entity",
            ),
        ),
        migrations.AlterField(
            model_name="update",
            name="frequency",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
