# -*- coding: utf-8 -*-
# Generated by Django 4.2.13 on 2024-07-03 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0035_alter_poll_entity_alter_poll_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datetimerange",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datetime_ranges",
                to="v1.column",
            ),
        ),
    ]
