# Generated by Django 4.2.13 on 2024-08-21 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0036_datetimerange_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='polls', to='v1.pipeline'),
        ),
    ]
