# Generated by Django 4.2.16 on 2024-11-03 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0037_area_entity_area_level_area_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="area",
            old_name="level",
            new_name="administrative_level",
        ),
    ]
