# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2024-05-10 16:00

from django.conf import settings
from django.db import migrations, models


def migrate_publishers_and_cleaners(apps, schema_editor):
    """Migrate existing ForeignKey relationships to ManyToMany"""
    Table = apps.get_model("v1", "Table")
    for table in Table.objects.all():
        # Store old ForeignKey values
        old_publisher = getattr(table, "published_by_old", None)
        old_cleaner = getattr(table, "data_cleaned_by_old", None)

        # Add to new M2M fields if they existed
        if old_publisher:
            table.published_by.add(old_publisher)
        if old_cleaner:
            table.data_cleaned_by.add(old_cleaner)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1", "0039_dataset_organizations"),
    ]

    operations = [
        # Rename old fields temporarily
        migrations.RenameField(
            model_name="table",
            old_name="published_by",
            new_name="published_by_old",
        ),
        migrations.RenameField(
            model_name="table",
            old_name="data_cleaned_by",
            new_name="data_cleaned_by_old",
        ),
        # Add new M2M fields
        migrations.AddField(
            model_name="table",
            name="published_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="tables_published",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Published by",
                help_text="People who published the table",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="data_cleaned_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="tables_cleaned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Data cleaned by",
                help_text="People who cleaned the data",
            ),
        ),
        # Run data migration
        migrations.RunPython(
            migrate_publishers_and_cleaners, reverse_code=migrations.RunPython.noop
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name="table",
            name="published_by_old",
        ),
        migrations.RemoveField(
            model_name="table",
            name="data_cleaned_by_old",
        ),
    ]
