# Generated by Django 4.2.16 on 2024-11-06 00:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0043_add_measurement_unit_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnitCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_pt', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_es', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Measurement Unit Category',
                'verbose_name_plural': 'Measurement Unit Categories',
                'db_table': 'measurement_unit_category',
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='tex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_units', to='v1.measurementunitcategory'),
        ),
    ]
