# Generated by Django 4.2.16 on 2024-11-06 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0048_alter_observationlevel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="polls",
                to="v1.pipeline",
            ),
        ),
    ]
