# Generated by Django 4.2.16 on 2024-12-08 03:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0052_remove_dataset_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='v1.area'),
        ),
        migrations.CreateModel(
            name='RawDataSourceComponent',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_pt', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_es', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_pt', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('raw_data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data_source_components', to='v1.rawdatasource')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_data_source_components', to='v1.status')),
            ],
            options={
                'verbose_name': 'Raw Data Source Component',
                'verbose_name_plural': 'Raw Data Source Components',
                'db_table': 'raw_data_source_component',
                'ordering': ['url'],
            },
        ),
        migrations.AddField(
            model_name='coverage',
            name='raw_data_source_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='v1.rawdatasourcecomponent'),
        ),
        migrations.AddField(
            model_name='observationlevel',
            name='raw_data_source_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_levels', to='v1.rawdatasourcecomponent'),
        ),
        migrations.AddField(
            model_name='poll',
            name='raw_data_source_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='v1.rawdatasourcecomponent'),
        ),
        migrations.AddField(
            model_name='update',
            name='raw_data_source_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='v1.rawdatasourcecomponent'),
        ),
    ]
