# -*- coding: utf-8 -*-
# Generated by Django 4.2.18 on 2025-02-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0052_remove_dataset_is_closed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawdatasource",
            name="required_registration",
        ),
        migrations.AddField(
            model_name="rawdatasource",
            name="requires_registration",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="organization",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="v1.area",
            ),
        ),
    ]
