# Generated by Django 4.2.16 on 2024-12-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0053_alter_organization_area_rawdatasourcecomponent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdatasource',
            old_name='required_registration',
            new_name='requires_registration',
        ),
    ]
