# -*- coding: utf-8 -*-
# Generated by Django 4.2.19 on 2025-02-22 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0053_rename_required_requires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="v1.area",
            ),
        ),
    ]
