# -*- coding: utf-8 -*-
# Generated by Django 4.2.19 on 2025-02-20 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0054_alter_key_options_alter_key_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Key",
            new_name="DictionaryKey",
        ),
        migrations.RenameField(
            model_name="coverage",
            old_name="key",
            new_name="dictionary_key",
        ),
        migrations.RenameField(
            model_name="qualitycheck",
            old_name="key",
            new_name="dictionary_key",
        ),
    ]
