# -*- coding: utf-8 -*-
# Generated by Django 4.2.19 on 2025-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0055_rename_key_dictionarykey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="is_data_api_endpoint",
            field=models.BooleanField(
                default=False, help_text="Table is served as an endpoint in our Data API."
            ),
        ),
    ]
