# -*- coding: utf-8 -*-
# Generated by Django 4.2.19 on 2025-02-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0055_alter_type_fields_many_tables"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Key",
            new_name="DictionaryKey",
        ),
        migrations.AlterModelOptions(
            name="dictionarykey",
            options={
                "ordering": ["name"],
                "verbose_name": "Dictionary Key",
                "verbose_name_plural": "Dictionary Keys",
            },
        ),
        migrations.RenameField(
            model_name="coverage",
            old_name="key",
            new_name="dictionary_key",
        ),
        migrations.RenameField(
            model_name="qualitycheck",
            old_name="key",
            new_name="dictionary_key",
        ),
        migrations.AddField(
            model_name="table",
            name="is_data_api_endpoint",
            field=models.BooleanField(
                default=False, help_text="Table is served as an endpoint in the Data API app."
            ),
        ),
        migrations.AlterModelTable(
            name="dictionarykey",
            table="dictionary_key",
        ),
    ]
