# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2026-10-07 02:32

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.custom.storage


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1", "0055_alter_type_fields_many_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "issn",
                    models.CharField(blank=True, max_length=9, null=True, verbose_name="ISSN"),
                ),
                (
                    "eissn",
                    models.CharField(blank=True, max_length=9, null=True, verbose_name="E-ISSN"),
                ),
                ("publisher", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
                "db_table": "journal",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Researcher",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=backend.custom.storage.OverwriteStorage(),
                        upload_to=backend.custom.storage.upload_to,
                        validators=[backend.custom.storage.validate_image],
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Current position, e.g. Assistant Professor",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "position_pt",
                    models.CharField(
                        blank=True,
                        help_text="Current position, e.g. Assistant Professor",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "position_en",
                    models.CharField(
                        blank=True,
                        help_text="Current position, e.g. Assistant Professor",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "position_es",
                    models.CharField(
                        blank=True,
                        help_text="Current position, e.g. Assistant Professor",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("phd_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Short blurb shown on the website", null=True
                    ),
                ),
                (
                    "description_pt",
                    models.TextField(
                        blank=True, help_text="Short blurb shown on the website", null=True
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True, help_text="Short blurb shown on the website", null=True
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True, help_text="Short blurb shown on the website", null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Public contact email. It is shown on the website",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("linkedin", models.URLField(blank=True, max_length=255, null=True)),
                ("google_scholar", models.URLField(blank=True, max_length=255, null=True)),
                ("lattes", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        help_text="ORCID iD, e.g. 0000-0002-1825-0097",
                        max_length=19,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        help_text="Data Basis user account, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="researcher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "affiliations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Universities or research institutes",
                        related_name="affiliated_researchers",
                        to="v1.organization",
                    ),
                ),
                (
                    "phd_institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phd_researchers",
                        to="v1.organization",
                        verbose_name="PhD institution",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Broad research fields",
                        related_name="researchers",
                        to="v1.theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Researcher",
                "verbose_name_plural": "Researchers",
                "db_table": "researcher",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchPaper",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                (
                    "authors",
                    models.TextField(
                        help_text="Full author list as cited, e.g. Silva, A. and Souza, B."
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("forthcoming", "Forthcoming"),
                            ("working_paper", "Working paper"),
                        ],
                        default="published",
                        max_length=32,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("volume", models.CharField(blank=True, max_length=32, null=True)),
                ("issue", models.CharField(blank=True, max_length=32, null=True)),
                ("pages", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="DOI without the resolver prefix, e.g. 10.1257/aer.20190001",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="DOI",
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
                ("google_scholar", models.URLField(blank=True, max_length=255, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "datasets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Datasets related to the paper, e.g. built from it or using it",
                        related_name="research_papers",
                        to="v1.dataset",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_papers",
                        to="v1.journal",
                    ),
                ),
                (
                    "researchers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Authors registered as researchers",
                        related_name="research_papers",
                        to="v1.researcher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Paper",
                "verbose_name_plural": "Research Papers",
                "db_table": "research_paper",
                "ordering": ["-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="InvitedResearcherTerm",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "cohort",
                    models.CharField(
                        blank=True,
                        help_text="Year and semester of the selection, e.g. 2027.1",
                        max_length=6,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}\\.[12]$", "Cohort must be a year and semester, e.g. 2027.1"
                            )
                        ],
                    ),
                ),
                ("start_at", models.DateField(help_text="Date of entry")),
                (
                    "end_at",
                    models.DateField(
                        blank=True,
                        help_text="Date of exit. Defaults to 2 years after the date of entry",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "researcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invited_researcher_terms",
                        to="v1.researcher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invited Researcher Term",
                "verbose_name_plural": "Invited Researcher Terms",
                "db_table": "invited_researcher_term",
                "ordering": ["-start_at"],
            },
        ),
    ]
