# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2026-10-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_data_tools", "0004_alter_disabledflowschedule_options"),
        ("v1", "0056_researchers_and_research_papers"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="flow_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tables",
                to="admin_data_tools.disabledflowschedule",
                verbose_name="Flow",
            ),
        ),
    ]
