# -*- coding: utf-8 -*-
# Generated by Django 4.2.4 on 2023-08-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_career_end_at_alter_career_start_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o usuário está ativo",
                verbose_name="Ativo",
            ),
        ),
    ]
