# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2024-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_account_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="available_for_research",
            field=models.TextField(
                blank=True,
                choices=[("YES", "Sim"), ("NO", "Não")],
                null=True,
                verbose_name="Se gostaria de participar de pesquisas",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="discovery_method",
            field=models.TextField(
                blank=True,
                choices=[
                    ("SOCIAL_MEDIA", "Redes sociais"),
                    ("REFERRAL", "Indicação"),
                    ("ONLINE_SEARCH", "Pesquisa online"),
                    ("EVENTS", "Eventos"),
                    ("ADVERTISING", "Publicidade"),
                    ("OTHER", "Outros"),
                ],
                null=True,
                verbose_name="Como conheceu a ONG",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="work_area",
            field=models.TextField(
                blank=True,
                choices=[
                    ("TECNOLOGIA", "Tecnologia"),
                    ("SAUDE", "Saúde"),
                    ("FINANCEIRO", "Financeiro"),
                    ("EDUCACAO", "Educação"),
                    ("VAREJO", "Varejo"),
                    ("ENERGIA", "Energia"),
                    ("JORNALISMO", "Jornalismo"),
                    ("OUTRA", "Outra"),
                ],
                null=True,
                verbose_name="Área",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="work_data_tool",
            field=models.TextField(
                blank=True,
                choices=[
                    ("SQL", "SQL"),
                    ("PYTHON", "Python"),
                    ("R", "R"),
                    ("STATA", "Stata"),
                    ("EXCEL", "Excel"),
                    ("NONE", "Nenhuma"),
                    ("OTHER", "Outra"),
                ],
                null=True,
                verbose_name="Ferramenta principal de análise de dados",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="work_goal",
            field=models.TextField(
                blank=True,
                choices=[
                    ("MARKET_ANALYSIS", "Análise de mercado"),
                    ("COMPETITOR_MONITORING", "Monitoramento de concorrência"),
                    ("ACADEMIC_RESEARCH", "Pesquisa acadêmica"),
                    ("RISK_MANAGEMENT", "Gestão de riscos"),
                    ("PRODUCT_DEVELOPMENT", "Desenvolvimento de produto"),
                    ("COMPLIANCE_REGULATORY", "Compliance e regulatório"),
                    ("PUBLIC_POLICY_ANALYSIS", "Análise de políticas públicas"),
                    ("OTHER", "Outro"),
                ],
                null=True,
                verbose_name="Objetivo com a ONG",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="work_role",
            field=models.TextField(
                blank=True,
                choices=[
                    ("CEO_DIRETOR", "CEO/Diretor(a)"),
                    ("GERENTE", "Gerente"),
                    ("COORDENADOR", "Coordenador(a)"),
                    ("ANALISTA", "Analista"),
                    ("CONSULTOR", "Consultor(a)"),
                    ("ESPECIALISTA", "Especialista"),
                    ("ASSISTENTE", "Assistente"),
                    ("ESTAGIARIO", "Estagiário(a)"),
                    ("ESTUDANTE", "Estudante"),
                    ("PROFESSOR_PESQUISADOR", "Professor(a)/Pesquisador(a)"),
                    ("FREELANCER", "Freelancer"),
                    ("EMPREENDEDOR", "Empreendedor(a)"),
                    ("OUTRO", "Outro"),
                ],
                null=True,
                verbose_name="Cargo",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="work_size",
            field=models.TextField(
                blank=True,
                choices=[
                    ("PEQUENA_1_10", "1-10 funcionários"),
                    ("PEQUENA_11_50", "11-50 funcionários"),
                    ("MEDIA_51_200", "51-200 funcionários"),
                    ("MEDIA_201_500", "201-500 funcionários"),
                    ("GRANDE_MAIS_500", "Mais de 500 funcionários"),
                ],
                null=True,
                verbose_name="Tamanho da empresa",
            ),
        ),
    ]
