# -*- coding: utf-8 -*-
# Generated by Django 4.2.16 on 2024-09-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0017_account_available_for_research_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="gcp_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="GCP email"
            ),
        ),
    ]
