# Generated by Django 4.2.18 on 2025-02-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0020_career_role_new"),
    ]

    operations = [
        migrations.RenameField(
            model_name="career",
            old_name="role",
            new_name="role_old",
        ),
        migrations.RenameField(
            model_name="career",
            old_name="team",
            new_name="team_old",
        ),
    ]
