# Generated by Django 4.2.18 on 2025-02-06 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0021_rename_role_career_role_old_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="career",
            old_name="role_new",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="career",
            old_name="team_new",
            new_name="team",
        ),
    ]
