# Generated by Django 4.2.18 on 2025-02-10 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_career_role_old_alter_career_team_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data API Key',
                'verbose_name_plural': 'Data API Keys',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='dataapikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration date', null=True),
        ),
        migrations.AddField(
            model_name='dataapikey',
            name='hashed_key',
            field=models.CharField(blank=True, help_text='The hashed API key', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dataapikey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataapikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataapikey',
            name='name',
            field=models.CharField(blank=True, help_text='A friendly name to identify this API key', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataapikey',
            name='prefix',
            field=models.CharField(blank=True, help_text='First 8 characters of the API key', max_length=8, null=True, unique=True),
        ),
    ]
