# -*- coding: utf-8 -*-
# ruff: noqa
# Generated by Django 4.2.26 on 2025-11-27 15:13

# NOTE: This migration was created automatically by the modeltranslation extension on 2025-02-04 but was not committed.
# Because our start-server.sh runs the makemigrations command, the migration file was created directly in the production
# pod and applied as 0021. This created divergences between our migration files in the repository and the actual state of
# the production database. We fixed this on December 17, 2025 by:
# 1. Deleting the original 0021 migration entry from the django_migrations table
# 2. Creating this migration file with the correct sequence number (0025)
# 3. Running a fake migration to register 0025 in django_migrations without re-executing the SQL

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0024_account_google_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="role",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="role",
            name="description_pt",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="role",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="role",
            name="name_es",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="role",
            name="name_pt",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="team",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="team",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="team",
            name="description_pt",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="team",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="team",
            name="name_es",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="team",
            name="name_pt",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
    ]
