# -*- coding: utf-8 -*-
# Generated by Django 4.2.18 on 2025-02-10 04:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0024_dataapikey"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataapikey",
            old_name="hashed_key",
            new_name="hash",
        ),
    ]
