# -*- coding: utf-8 -*-
# Generated by Django 4.2.21 on 2025-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0024_role_description_en_role_description_es_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="has_access_to_chatbot",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o usuário tem acesso ao chatbot",
                verbose_name="Tem acesso ao chatbot",
            ),
        ),
    ]
