# -*- coding: utf-8 -*-
# Generated by Django 4.2.18 on 2025-02-12 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0025_rename_hashed_key_hash"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataAPIKey",
        ),
    ]
