# Generated by Django 4.2.21 on 2025-05-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_account_has_access_to_chatbot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='has_access_to_chatbot',
            new_name='has_chatbot_access',
        ),
    ]
