# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2025-12-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0025_account_google_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="role",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="role",
            name="description_pt",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="role",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="role",
            name="name_es",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="role",
            name="name_pt",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="team",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="team",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="team",
            name="description_pt",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="team",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="team",
            name="name_es",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="team",
            name="name_pt",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
    ]
