# -*- coding: utf-8 -*-
# Generated by Django 4.2.18 on 2025-02-20 11:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0026_delete_dataapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="role",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="role",
            name="description_pt",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="role",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="role",
            name="name_es",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="role",
            name="name_pt",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="team",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="team",
            name="description_es",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="team",
            name="description_pt",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="team",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="team",
            name="name_es",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="team",
            name="name_pt",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Name"),
        ),
        migrations.CreateModel(
            name="DataAPIKey",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="A friendly name to identify this API key",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "hashed_key",
                    models.CharField(
                        blank=True,
                        help_text="The hashed API key",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="First 8 characters of the API key",
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiration date", null=True
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="data_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data API Key",
                "verbose_name_plural": "Data API Keys",
                "ordering": ["created_at"],
            },
        ),
    ]
