# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2026-02-12 15:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0027_rename_has_access_to_chatbot_account_has_chatbot_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
