# -*- coding: utf-8 -*-
# Generated by Django 4.2.19 on 2025-02-20 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0027_role_description_en_role_description_es_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DataAPIKey",
        ),
    ]
