# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-05-06 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1", "0012_analysis_description_analysis_description_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="published_by",
        ),
        migrations.AddField(
            model_name="analysis",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                help_text="People who performed and/or wrote the analysis",
                related_name="analyses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="qualitycheck",
            name="passed",
            field=models.BooleanField(default=False, help_text="Passed the quality check"),
        ),
    ]
