# -*- coding: utf-8 -*-
# Generated by Django 4.2.14 on 2024-07-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("execution_time", models.DateTimeField()),
                ("duration", models.FloatField(default=0)),
                ("status", models.CharField(max_length=255)),
                ("result", models.TextField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tarefa executada",
                "verbose_name_plural": "Tarefas executadas",
                "ordering": ["-execution_time"],
            },
        ),
    ]
