# -*- coding: utf-8 -*-
# Generated by Django 4.2.14 on 2024-07-19 13:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_taskexecution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecution",
            name="execution_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
