# -*- coding: utf-8 -*-
# Generated by Django 4.2.14 on 2024-07-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_taskexecution_execution_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecution",
            name="status",
            field=models.CharField(default="running", max_length=100),
        ),
    ]
