# -*- coding: utf-8 -*-
# ruff: noqa
# Generated by Django 4.2.10 on 2026-01-14 18:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1", "0055_alter_type_fields_many_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableUpdateSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deactivate_at", models.DateTimeField(blank=True, null=True)),
                ("last_notification", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "table",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="v1.table"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Table Update Subscription",
                "verbose_name_plural": "Table Update Subscriptions",
            },
        ),
    ]
