# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2025-12-02 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1", "0055_alter_type_fields_many_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableUpdateSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "table",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="v1.table"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Table Update Subscription",
                "verbose_name_plural": "Table Update Subscriptions",
            },
        ),
    ]
