# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2025-12-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tableupdatesubscription",
            old_name="deleted_at",
            new_name="deactivate_at",
        ),
        migrations.AddField(
            model_name="tableupdatesubscription",
            name="last_notification",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tableupdatesubscription",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
