# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2025-12-10 04:21
# ruff: noqa

from django.db import migrations


def alter_id_field(apps, schema_editor):
    # Obter o modelo para alteração
    MeuModelo = apps.get_model("user_notifications", "TableUpdateSubscription")

    # Alterar o campo ID para UUID manualmente, com um script SQL
    with schema_editor.connection.cursor() as cursor:
        # 1. Adicionar nova coluna UUID
        cursor.execute(
            f"ALTER TABLE {MeuModelo._meta.db_table} ADD COLUMN new_id UUID DEFAULT uuid_generate_v4()"
        )

        # 2. Definir a nova coluna como PRIMARY KEY
        cursor.execute(
            f"ALTER TABLE {MeuModelo._meta.db_table} ADD CONSTRAINT new_id_primary_key PRIMARY KEY (new_id)"
        )

        # 3. Remover a coluna antiga (id)
        cursor.execute(f"ALTER TABLE {MeuModelo._meta.db_table} DROP COLUMN id")

        # 4. Renomear a nova coluna para 'id'
        cursor.execute(f"ALTER TABLE {MeuModelo._meta.db_table} RENAME COLUMN new_id TO id")


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_notifications",
            "0002_rename_deleted_at_tableupdatesubscription_deactivate_at_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(alter_id_field),
    ]
