# -*- coding: utf-8 -*-
# Generated by Django 4.1.7 on 2023-05-01 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0006_alter_dataset_tags_alter_dataset_themes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entitycategory",
            options={
                "ordering": ["slug"],
                "verbose_name": "Entity Category",
                "verbose_name_plural": "Entity Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="observationlevel",
            options={
                "ordering": ["id"],
                "verbose_name": "Observation Level",
                "verbose_name_plural": "Observation Levels",
            },
        ),
        migrations.AlterModelTable(
            name="observationlevel",
            table="observation_level",
        ),
    ]
