# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0011_alter_analysis_options_analysis_datasets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysis",
            name="description_pt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualitycheck",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualitycheck",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualitycheck",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualitycheck",
            name="description_pt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
