# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-05-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0016_column_is_primary_key_column_version_dataset_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudtable",
            name="columns",
            field=models.ManyToManyField(blank=True, related_name="cloud_tables", to="v1.column"),
        ),
    ]
