# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-06-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0017_alter_cloudtable_columns"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawdatasource",
            old_name="contains_structure_data",
            new_name="contains_structured_data",
        ),
    ]
