# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "v1",
            "0018_rename_contains_structure_data_rawdatasource_contains_structured_data",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="column",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
