# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-12-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0025_alter_coverage_area_columnoriginalname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="source_bucket_name",
            field=models.CharField(blank=True, default="basedosdados", max_length=255, null=True),
        ),
    ]
