# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2024-03-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0027_dataset_page_views_table_page_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableNeighbor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity", models.FloatField(default=0)),
                ("similarity_of_area", models.FloatField(default=0)),
                ("similarity_of_datetime", models.FloatField(default=0)),
                ("similarity_of_directory", models.FloatField(default=0)),
                (
                    "table_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tableneighbor_a_set",
                        to="v1.table",
                    ),
                ),
                (
                    "table_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tableneighbor_b_set",
                        to="v1.table",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tableneighbor",
            constraint=models.UniqueConstraint(
                fields=("table_a", "table_b"), name="table_neighbor_unique_constraint"
            ),
        ),
    ]
