# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2024-04-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0028_tableneighbor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="one_big_table_query",
            field=models.TextField(blank=True, null=True),
        ),
    ]
