# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2024-04-26 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0029_table_one_big_table_query"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="one_big_table_query",
        ),
    ]
