# Generated by Django 4.2.10 on 2024-05-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0030_remove_table_one_big_table_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="raw_data_source",
            field=models.ManyToManyField(
                blank=True, related_name="tables", to="v1.rawdatasource"
            ),
        ),
    ]
