# -*- coding: utf-8 -*-
# Generated by Django 4.2.18 on 2025-02-12 07:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndpointCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_pt", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("name_es", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_pt", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Endpoint Category",
                "verbose_name_plural": "Endpoint Categories",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterField(
            model_name="key",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="key",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="The balance of the key in BRL",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="key",
            name="hash",
            field=models.CharField(
                blank=True, help_text="The hashed key", max_length=64, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="key",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A friendly name to identify this key",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="key",
            name="prefix",
            field=models.CharField(
                blank=True,
                help_text="First 8 characters of the key",
                max_length=8,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="endpoints",
                to="data_api.endpointcategory",
            ),
        ),
    ]
