# -*- coding: utf-8 -*-
# Generated by Django 4.2.18 on 2025-02-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_api", "0002_endpointcategory_alter_key_account_alter_key_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
        migrations.AddField(
            model_name="endpointcategory",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
    ]
