# -*- coding: utf-8 -*-
# Generated by Django 4.2.18 on 2025-02-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_api", "0003_endpoint_slug_endpointcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="currency",
            field=models.ForeignKey(
                limit_choices_to={"category__slug": "currency"},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="credits",
                to="v1.measurementunit",
            ),
        ),
        migrations.AlterField(
            model_name="endpointpricingtier",
            name="currency",
            field=models.ForeignKey(
                limit_choices_to={"category__slug": "currency"},
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="endpoint_pricing_tiers",
                to="v1.measurementunit",
            ),
        ),
    ]
