# -*- coding: utf-8 -*-
# Generated by Django 4.2.19 on 2025-02-21 07:33

import django.db.models.deletion
from django.db import migrations, models

import backend.apps.data_api.models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0056_table_is_data_api_endpoint"),
        ("data_api", "0004_alter_credit_currency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endpointparameter",
            old_name="required",
            new_name="is_required",
        ),
        migrations.AddField(
            model_name="endpoint",
            name="table",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=backend.apps.data_api.models.limit_table_choices,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="endpoints",
                to="v1.table",
            ),
        ),
        migrations.AddField(
            model_name="endpointcategory",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="endpoint_categories",
                to="v1.dataset",
            ),
        ),
        migrations.AddField(
            model_name="endpointparameter",
            name="column",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=backend.apps.data_api.models.limit_column_choices,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="parameters",
                to="v1.column",
            ),
        ),
    ]
