# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2022-12-21 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawDataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_pt", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("raw_data_url", models.URLField(blank=True, null=True)),
                ("auxiliary_files_url", models.URLField(blank=True, null=True)),
                ("architecture_url", models.URLField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_data_sources",
                        to="v1.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Data Source",
                "verbose_name_plural": "Raw Data Sources",
                "db_table": "raw_data_source",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="InformationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_pt", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("raw_data_url", models.URLField(blank=True, null=True)),
                ("auxiliary_files_url", models.URLField(blank=True, null=True)),
                ("architecture_url", models.URLField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="information_requests",
                        to="v1.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Information Request",
                "verbose_name_plural": "Information Requests",
                "db_table": "information_request",
                "ordering": ["slug"],
            },
        ),
    ]
