# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2023-02-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="column",
            name="coverages",
        ),
        migrations.RemoveField(
            model_name="coverage",
            name="temporal_coverages",
        ),
        migrations.RemoveField(
            model_name="informationrequest",
            name="coverages",
        ),
        migrations.RemoveField(
            model_name="key",
            name="coverages",
        ),
        migrations.RemoveField(
            model_name="rawdatasource",
            name="coverages",
        ),
        migrations.RemoveField(
            model_name="table",
            name="coverages",
        ),
        migrations.AddField(
            model_name="coverage",
            name="column",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="v1.column",
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="information_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="v1.informationrequest",
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="v1.key",
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="raw_data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="v1.rawdatasource",
            ),
        ),
        migrations.AddField(
            model_name="coverage",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="v1.table",
            ),
        ),
        migrations.AddField(
            model_name="temporalcoverage",
            name="coverage",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temporal_coverages",
                to="v1.coverage",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="temporalcoverage",
            name="interval",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporalcoverage",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="temporalcoverage",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
