# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2023-01-19 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0002_rawdatasource_informationrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_pt", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "db_table": "area",
                "ordering": ["slug"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="area",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="v1.area",
            ),
            preserve_default=False,
        ),
    ]
