# Generated by Django 4.1.7 on 2023-03-17 21:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0002_remove_informationrequest_entities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_pt", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_es", models.CharField(max_length=255, null=True)),
            ],
            options={
                "verbose_name": "EntityCategory",
                "verbose_name_plural": "EntityCategories",
                "db_table": "entity_category",
                "ordering": ["slug"],
            },
        ),
        migrations.RemoveField(
            model_name="entity",
            name="category_en",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="category_es",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="category_pt",
        ),
        migrations.AlterField(
            model_name="entity",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="v1.entitycategory",
            ),
        ),
    ]
