# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2023-02-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0002_remove_column_coverages_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawdatasource",
            options={
                "ordering": ["url"],
                "verbose_name": "Raw Data Source",
                "verbose_name_plural": "Raw Data Sources",
            },
        ),
        migrations.RemoveField(
            model_name="rawdatasource",
            name="slug",
        ),
        migrations.AddField(
            model_name="rawdatasource",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
