# Generated by Django 4.1.7 on 2023-03-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0002_alter_dataset_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
