# Generated by Django 4.1.7 on 2023-03-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0003_entitycategory_remove_entity_category_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
