# Generated by Django 4.1.3 on 2023-02-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0003_alter_rawdatasource_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informationrequest",
            name="observation_level",
        ),
        migrations.RemoveField(
            model_name="rawdatasource",
            name="observation_level",
        ),
        migrations.AddField(
            model_name="informationrequest",
            name="entities",
            field=models.ManyToManyField(
                blank=True, related_name="information_requests", to="v1.entity"
            ),
        ),
        migrations.AddField(
            model_name="rawdatasource",
            name="entities",
            field=models.ManyToManyField(
                blank=True, related_name="raw_data_sources", to="v1.entity"
            ),
        ),
    ]
