# -*- coding: utf-8 -*-
# Generated by Django 4.1.7 on 2023-04-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0003_alter_column_is_closed_alter_dataset_is_closed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dictionary",
            options={
                "ordering": ["column"],
                "verbose_name": "Dictionary",
                "verbose_name_plural": "Dictionaries",
            },
        ),
    ]
