# Generated by Django 4.1.7 on 2023-03-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0004_alter_table_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="updatefrequency",
            options={
                "ordering": ["number"],
                "verbose_name": "Update",
                "verbose_name_plural": "Updates",
            },
        ),
        migrations.RemoveField(
            model_name="informationrequest",
            name="update_frequency",
        ),
        migrations.RemoveField(
            model_name="rawdatasource",
            name="update_frequency",
        ),
        migrations.RemoveField(
            model_name="table",
            name="update_frequency",
        ),
        migrations.AddField(
            model_name="informationrequest",
            name="update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information_requests",
                to="v1.updatefrequency",
            ),
        ),
        migrations.AddField(
            model_name="rawdatasource",
            name="update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_data_sources",
                to="v1.updatefrequency",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="v1.updatefrequency",
            ),
        ),
        migrations.AddField(
            model_name="updatefrequency",
            name="lag",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="updatefrequency",
            name="last",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="updatefrequency",
            table="update",
        ),
    ]
