# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2022-12-14 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0004_alter_column_id_alter_dataset_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BigQueryTypes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "BigQuery Type",
                "verbose_name_plural": "BigQuery Types",
                "db_table": "bigquery_types",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="cloudtable",
            options={
                "ordering": ["id"],
                "verbose_name": "Cloud Table",
                "verbose_name_plural": "Cloud Tables",
            },
        ),
        migrations.AlterModelOptions(
            name="column",
            options={
                "ordering": ["slug"],
                "verbose_name": "Column",
                "verbose_name_plural": "Columns",
            },
        ),
        migrations.AlterModelOptions(
            name="dataset",
            options={
                "ordering": ["slug"],
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["slug"],
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["slug"],
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
            },
        ),
        migrations.AddField(
            model_name="cloudtable",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="column",
            name="coverage_by_dictionary",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="has_sensitive_data",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="is_in_staging",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="column",
            name="is_partition",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="column",
            name="measurement_unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="name_en",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="column",
            name="name_pt",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="column",
            name="observations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="column",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataset",
            name="name_en",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataset",
            name="name_pt",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataset",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="name_en",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="name_pt",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="architecture_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="auxiliary_files_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="compressed_file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="data_cleaned_code_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="data_cleaned_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="is_directory",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="name_en",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="name_pt",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="number_of_rows",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="raw_data_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="source_bucket_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="uncompressed_file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="cloudtable",
            name="table",
        ),
        migrations.AddField(
            model_name="column",
            name="bigquery_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="v1.bigquerytypes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cloudtable",
            name="table",
            field=models.ManyToManyField(related_name="cloud_table", to="v1.table"),
        ),
    ]
