# Generated by Django 4.1.7 on 2023-04-30 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0004_alter_dictionary_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="v1.license",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="partner_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_tables",
                to="v1.organization",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="v1.pipeline",
            ),
        ),
    ]
