# Generated by Django 4.1.7 on 2023-03-24 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0004_alter_table_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("frequency", models.IntegerField()),
                ("lag", models.IntegerField(blank=True, null=True)),
                ("last", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="v1.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Update",
                "verbose_name_plural": "Updates",
                "db_table": "update",
                "ordering": ["frequency"],
            },
        ),
        migrations.RemoveField(
            model_name="informationrequest",
            name="update_frequency",
        ),
        migrations.RemoveField(
            model_name="rawdatasource",
            name="update_frequency",
        ),
        migrations.RemoveField(
            model_name="table",
            name="update_frequency",
        ),
        migrations.DeleteModel(
            name="UpdateFrequency",
        ),
        migrations.AddField(
            model_name="informationrequest",
            name="update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information_requests",
                to="v1.update",
            ),
        ),
        migrations.AddField(
            model_name="rawdatasource",
            name="update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_data_sources",
                to="v1.update",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="v1.update",
            ),
        ),
    ]
