# Generated by Django 4.1.3 on 2023-01-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0005_remove_area_area_ip_address_required_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availability",
            options={
                "ordering": ["slug"],
                "verbose_name": "Availability",
                "verbose_name_plural": "Availabilities",
            },
        ),
        migrations.AlterModelOptions(
            name="language",
            options={
                "ordering": ["slug"],
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.AlterModelTable(
            name="availability",
            table="availability",
        ),
        migrations.AlterModelTable(
            name="language",
            table="language",
        ),
    ]
