# Generated by Django 4.1.3 on 2023-02-24 20:10

import basedosdados_api.api.v1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0005_datetimerange_delete_temporalcoverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="key",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    basedosdados_api.api.v1.validators.validate_area_key,
                    basedosdados_api.api.v1.validators.validate_is_valid_area_key,
                ],
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="name",
            field=models.CharField(default="undefined", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="area",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="area",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
