# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2022-12-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0005_bigquerytypes_alter_cloudtable_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cloudtable",
            old_name="table",
            new_name="tables",
        ),
    ]
