# Generated by Django 4.1.7 on 2023-03-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0005_update_remove_informationrequest_update_frequency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="update",
            old_name="last",
            new_name="latest",
        ),
    ]
