# Generated by Django 4.1.7 on 2023-03-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0005_alter_updatefrequency_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="updatefrequency",
            old_name="last",
            new_name="last_update",
        ),
    ]
