# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2022-12-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0006_rename_table_cloudtable_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudtable",
            name="tables",
            field=models.ManyToManyField(related_name="cloud_tables", to="v1.table"),
        ),
    ]
