# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2023-02-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0006_alter_availability_options_alter_language_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="column",
            options={
                "ordering": ["name_pt"],
                "verbose_name": "Column",
                "verbose_name_plural": "Columns",
            },
        ),
        migrations.RemoveField(
            model_name="column",
            name="slug",
        ),
        migrations.AddField(
            model_name="informationrequest",
            name="observations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="informationrequest",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="license",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="rawdatasource",
            name="area_ip_address_required",
        ),
        migrations.AddField(
            model_name="rawdatasource",
            name="area_ip_address_required",
            field=models.ManyToManyField(
                blank=True, related_name="raw_data_sources", to="v1.area"
            ),
        ),
    ]
