# Generated by Django 4.1.7 on 2023-03-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0006_rename_last_update_latest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informationrequest",
            name="update",
        ),
        migrations.RemoveField(
            model_name="rawdatasource",
            name="update",
        ),
        migrations.RemoveField(
            model_name="table",
            name="update",
        ),
        migrations.AddField(
            model_name="update",
            name="information_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="v1.informationrequest",
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="raw_data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="v1.rawdatasource",
            ),
        ),
        migrations.AddField(
            model_name="update",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="v1.table",
            ),
        ),
    ]
