# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2023-02-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0007_alter_column_options_remove_column_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysistype",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analysistype",
            name="tag",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="availability",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="column",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dataset",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entity",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="informationrequest",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="language",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rawdatasource",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="status",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="theme",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeunit",
            name="name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysistype",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="analysistype",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="analysistype",
            name="tag_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="analysistype",
            name="tag_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="availability",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="availability",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="column",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="column",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="informationrequest",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="informationrequest",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdatasource",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="rawdatasource",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="theme",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="theme",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="timeunit",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="timeunit",
            name="name_pt",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
