# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2022-12-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0007_alter_cloudtable_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cloudtable",
            name="tables",
        ),
        migrations.AddField(
            model_name="cloudtable",
            name="table",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cloud_tables",
                to="v1.table",
            ),
            preserve_default=False,
        ),
    ]
