# -*- coding: utf-8 -*-
# Generated by Django 4.1.3 on 2023-03-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0007_alter_table_slug_table_constraint_dataset_table_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationrequest",
            name="data_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="informationrequest",
            name="origin",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
