# Generated by Django 4.1.3 on 2023-02-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0008_alter_area_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="key",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
