# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-05-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0008_analysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysistype",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="analysistype",
            name="tag_en",
        ),
        migrations.RemoveField(
            model_name="analysistype",
            name="tag_es",
        ),
        migrations.RemoveField(
            model_name="analysistype",
            name="tag_pt",
        ),
    ]
