# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-05-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0009_remove_analysistype_tag_remove_analysistype_tag_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags are used to group analyses by topic",
                related_name="analyses",
                to="v1.tag",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="themes",
            field=models.ManyToManyField(
                help_text="Themes are used to group analyses by topic",
                related_name="analyses",
                to="v1.theme",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coverage",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverages",
                to="v1.analysis",
            ),
        ),
        migrations.AddField(
            model_name="observationlevel",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observation_levels",
                to="v1.analysis",
            ),
        ),
    ]
