# Generated by Django 4.1.3 on 2023-02-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0007_alter_table_slug_table_constraint_dataset_table_slug"),
        ("v1", "0010_alter_area_key"),
    ]

    operations = []
