# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-06-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0020_table_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationrequest",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rawdatasource",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
