# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-07-09 21:32

import basedosdados_api.account.storage
import basedosdados_api.api.v1.models
import basedosdados_api.api.v1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0022_alter_column_is_closed_alter_dataset_is_closed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=basedosdados_api.account.storage.OverwriteStorage(),
                upload_to=basedosdados_api.api.v1.models.image_path_and_rename,
                validators=[
                    basedosdados_api.api.v1.validators.validate_is_valid_image_format
                ],
                verbose_name="Image",
            ),
        ),
    ]
