# Generated by Django 4.1.7 on 2023-03-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0001_initial"),
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                related_query_name="user",
                to="v1.organization",
                verbose_name="Organizações",
            ),
        ),
    ]
