# Generated by Django 4.1.7 on 2023-03-16 19:29

import basedosdados_api.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=basedosdados_api.account.models.image_path_and_rename,
                verbose_name="Imagem",
            ),
        ),
    ]
