# Generated by Django 4.1.7 on 2023-03-13 02:37

import basedosdados_api.account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("v1", "0001_initial"),
        ("account", "0003_alter_account_organizations"),
    ]

    operations = [
        migrations.CreateModel(
            name="BDGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "BD group",
                "verbose_name_plural": "BD groups",
            },
            managers=[
                ("objects", basedosdados_api.account.models.BDGroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="BDRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        related_query_name="role",
                        to="auth.permission",
                        verbose_name="Permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "BD role",
                "verbose_name_plural": "BD roles",
            },
            managers=[
                ("objects", basedosdados_api.account.models.BDRoleManager()),
            ],
        ),
        migrations.CreateModel(
            name="BDGroupRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.bdgroup",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_roles",
                        related_query_name="group_role",
                        to="v1.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.bdrole"
                    ),
                ),
            ],
            options={
                "verbose_name": "BD group role",
                "verbose_name_plural": "BD group roles",
            },
        ),
        migrations.AddField(
            model_name="bdgroup",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                related_query_name="group",
                through="account.BDGroupRole",
                to="account.bdrole",
                verbose_name="Roles",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                related_query_name="user",
                to="account.bdgroup",
                verbose_name="Grupos",
            ),
        ),
        migrations.AddConstraint(
            model_name="bdgrouprole",
            constraint=models.UniqueConstraint(
                fields=("group", "role", "organization"),
                name="unique_group_role_organization",
            ),
        ),
    ]
