# -*- coding: utf-8 -*-
# Generated by Django 4.1.7 on 2023-03-31 14:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_account_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="ckan_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
