# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-05-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("account", "0004_account_ckan_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="ckan_id",
            new_name="uuid",
        ),
        migrations.AddField(
            model_name="account",
            name="staff_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Grupos de acesso ao admin",
                related_name="users",
                related_query_name="user",
                to="auth.group",
                verbose_name="Grupos Internos",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Grupos de acesso ao app externo da BD",
                related_name="users",
                related_query_name="user",
                to="account.bdgroup",
                verbose_name="Grupos Externos",
            ),
        ),
    ]
