# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-08-13 17:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_rename_ckan_id_account_uuid_account_staff_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                (
                    "team",
                    models.CharField(blank=True, max_length=40, verbose_name="Equipe"),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=40, verbose_name="Cargo"),
                ),
                (
                    "level",
                    models.CharField(blank=True, max_length=40, verbose_name="Nível"),
                ),
                (
                    "start_at",
                    models.DateField(null=True, verbose_name="Data de Início"),
                ),
                ("end_at", models.DateField(null=True, verbose_name="Data de Término")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Career",
                "verbose_name_plural": "Careers",
            },
        ),
    ]
