# -*- coding: utf-8 -*-
# Generated by Django 4.2.5 on 2023-10-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_career_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Indica se tem acesso à administração",
                verbose_name="Admin",
            ),
        ),
    ]
