# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-11-29 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_subscription_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="internal_subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
