# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2023-12-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0014_alter_subscription_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_email_visible",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o email do usuário é público",
                verbose_name="Email é visível",
            ),
        ),
    ]
