# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2024-01-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_account_is_email_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
