# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2026-04-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisabledFlowSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("flow_name", models.CharField(max_length=255, unique=True)),
                ("flow_id", models.CharField(max_length=255)),
                ("disabled_at", models.DateTimeField(auto_now_add=True)),
                ("is_schedule_active", models.BooleanField(default=False)),
                ("reactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Disabled Flow Schedule",
                "verbose_name_plural": "Disabled Flow Schedules",
                "ordering": ["-disabled_at"],
            },
        ),
    ]
