# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2026-07-06 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_data_tools", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="disabledflowschedule",
            old_name="flow_id",
            new_name="deployment_id",
        ),
    ]
