# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2026-07-07 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admin_data_tools",
            "0002_rename_flow_id_disabledflowschedule_deployment_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="disabledflowschedule",
            name="disabled_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
