# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2026-08-22 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_data_tools", "0003_alter_disabledflowschedule_disabled_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disabledflowschedule",
            options={
                "ordering": ["-disabled_at"],
                "verbose_name": "Flow Schedule",
                "verbose_name_plural": "Flow Schedules",
            },
        ),
    ]
