apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.api.name }}-service"
  labels:
    app.kubernetes.io/component: basedosdados-api
    app.kubernetes.io/name: {{ .Values.api.name }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/component: basedosdados-api
    app.kubernetes.io/name: {{ .Values.api.name }}
