# -*- coding: utf-8 -*-
# Generated by Django 4.2.20 on 2025-04-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
