# -*- coding: utf-8 -*-
# Generated by Django 4.2.21 on 2025-05-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_alter_feedback_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="sync_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("success", "Success"), ("failed", "Failed")],
                default="pending",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
