# -*- coding: utf-8 -*-
# Generated by Django 4.2.21 on 2025-05-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0003_feedback_sync_status_feedback_synced_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="sync_status",
            field=models.TextField(
                choices=[("pending", "Pending"), ("success", "Success"), ("failed", "Failed")],
                default="pending",
            ),
        ),
    ]
