# -*- coding: utf-8 -*-
# Generated by Django 4.2.23 on 2025-07-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0004_alter_feedback_sync_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
