# -*- coding: utf-8 -*-
# Generated by Django 4.2.23 on 2025-07-07 20:49

from django.db import migrations, models


def populate_thread_titles(apps, schema_editor):
    Thread = apps.get_model("chatbot", "Thread")
    MessagePair = apps.get_model("chatbot", "MessagePair")
    db_alias = schema_editor.connection.alias

    for thread in Thread.objects.using(db_alias).all():
        message_pair = (
            MessagePair.objects.filter(thread_id=thread.id).order_by("created_at").first()
        )

        if message_pair:
            thread.title = message_pair.user_message
        else:
            thread.title = "Sem título"

        thread.save(update_fields=["title"])


def noop_reverse(apps, schema_editor):
    # The reverse migration will be done by removing the
    # 'deleted' and 'title' fields, so no action needed here.
    ...


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0004_alter_feedback_sync_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.RunPython(
            code=populate_thread_titles,
            reverse_code=noop_reverse,
        ),
        migrations.AlterField(
            model_name="thread",
            name="title",
            field=models.TextField(null=False),
        ),
        migrations.AddField(
            model_name="thread",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
