# -*- coding: utf-8 -*-
# Generated by Django 4.2.23 on 2025-07-18 16:23

from django.db import migrations, models


def noop_forward(apps, schema_editor):
    # The migration will be done by just creating the 'error_message' and 'steps' fields
    # and by making the 'assistant_message' field nullable, so no action needed here.
    ...


def populate_assistant_messages(apps, schema_editor):
    MessagePair = apps.get_model("chatbot", "MessagePair")
    db_alias = schema_editor.connection.alias

    for mp in MessagePair.objects.using(db_alias).all():
        if mp.assistant_message is None:
            mp.assistant_message = mp.error_message
            mp.save(update_fields=["assistant_message"])


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0005_thread_title_thread_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagepair",
            name="error_message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="messagepair",
            name="steps",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="messagepair",
            name="assistant_message",
            field=models.TextField(null=True),
        ),
        migrations.RunPython(
            code=noop_forward,
            reverse_code=populate_assistant_messages,
        ),
        migrations.AddConstraint(
            model_name="messagepair",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("assistant_message__isnull", False),
                    ("error_message__isnull", False),
                    _connector="XOR",
                ),
                name="check_exactly_one_response",
            ),
        ),
    ]
