# -*- coding: utf-8 -*-
# Generated by Django 4.2.23 on 2025-07-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0005_thread_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
