# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2025-08-27 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0006_messagepair_error_message_messagepair_steps_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messagepair",
            old_name="steps",
            new_name="events",
        ),
    ]
