# -*- coding: utf-8 -*-
# Generated by Django 4.2.10 on 2025-11-26 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0007_rename_steps_messagepair_events"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagepair",
            name="generated_chart",
        ),
        migrations.RemoveField(
            model_name="messagepair",
            name="generated_queries",
        ),
    ]
