# Generated by Django 4.2.10 on 2026-03-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_messagepair_generated_chart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagepair',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='account',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='MessagePair',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS checkpoint_blobs;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS checkpoint_writes;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS checkpoints;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS checkpoint_migrations;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
