# -*- coding: utf-8 -*-
# Generated by Django 4.2.1 on 2023-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0022_coverage_is_closed_alter_column_is_closed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datetimerange",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="Is Closed"),
        ),
    ]
