name: Deployment - Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import secrets from Vault
        id: import_secrets
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: https://vault.dados.rio
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/github_actions_deployment_secrets  GCP_PROJECT_ID   | GCP_PROJECT_ID ;
            secret/data/github_actions_deployment_secrets  GCP_SA_KEY       | GCP_SA_KEY ;
            secret/data/github_actions_deployment_secrets  GH_PAT           | GH_PAT ;
            secret/data/github_actions_deployment_secrets  GKE_CLUSTER      | GKE_CLUSTER ;
            secret/data/github_actions_deployment_secrets  GKE_ZONE         | GKE_ZONE ;

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ steps.import_secrets.outputs.GCP_SA_KEY }}
          project_id: ${{ steps.import_secrets.outputs.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ steps.import_secrets.outputs.GKE_CLUSTER }}
          location: ${{ steps.import_secrets.outputs.GKE_ZONE }}
          credentials: ${{ steps.import_secrets.outputs.GCP_SA_KEY }}

      - name: Write values.yaml file
        run: |
          cat << EOF > values.yaml
          image:
            repository: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
            tag: pr-${{ github.event.number }}
          EOF

      - name: Wait for Docker image release
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.ref }}
          check-name: 'Docker - Release image'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          verbose: true

      - name: Deploy using Helm
        uses: deliverybot/helm@v1
        with:
          release: staging-backend
          namespace: staging-backend-dados-rio
          chart: ./charts/basedosdados-api
          value-files: >-
            [
              "values.yaml"
            ]
          token: ${{ github.token }}
