---
name: CI Docker
on:
  pull_request:
    paths: [Dockerfile]
jobs:
  lint:
    name: Lint dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
