name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x64]
        os: [ubuntu-latest]
        python-version: ["3.11.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint source code
        uses: chartboost/ruff-action@v1
      - name: Lint pull request title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x64]
        os: [ubuntu-latest]
        python-version: ["3.11.x"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          architecture: ${{ matrix.arch }}
          python-version: ${{ matrix.python-version }}
      - name: Set up poetry and upgrade pip
        run: pip install -U pip poetry
      - name: Install this package
        run: poetry install
      - name: Test
        run: |
          poetry run pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov=bd_api bd_api | tee pytest-coverage.txt
      - name: Report coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-report: true
          junitxml-path: ./pytest.xml
          pytest-coverage-path: ./pytest-coverage.txt
